"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "fr" | "ar" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Flattened translations object for direct lookup
const translations = {
  // Navigation
  "nav.home": "Accueil",
  "nav.catalog": "Catalogue",
  "nav.how_it_works": "Comment ça marche",
  "nav.about": "À propos",
  "nav.contact": "Contact",
  "nav.client_portal": "Portail client",
  "nav.login": "Se connecter",

  // Hero section
  "hero.title": "Location d'équipements informatiques pour entreprises",
  "hero.subtitle":
    "Louez vos équipements IT services inclus. Flexibilité, performance et tranquillité d'esprit pour votre entreprise.",
  "hero.cta_primary": "Découvrir le catalogue",
  "hero.cta_secondary": "Comment ça marche",

  // Categories section
  "categories.title": "Notre catalogue d'équipements",
  "categories.subtitle": "Découvrez notre gamme complète d'équipements informatiques professionnels",

  // Features section
  "features.title": "Pourquoi choisir Ekwip ?",
  "features.subtitle": "Des solutions flexibles pour équiper votre entreprise sans contrainte",
  "features.flexibility.title": "Préservez votre trésorerie",
  "features.flexibility.desc":
    "Transformez vos dépenses d'investissement en coûts opérationnels prévisibles avec des mensualités fixes.",
  "features.maintenance.title": "Support et maintenance inclus",
  "features.maintenance.desc": "Assistance technique et remplacement rapide en cas de problème.",
  "features.upgrade.title": "Upgradez à tout moment",
  "features.upgrade.desc": "Échangez ou upgradez votre équipement selon vos besoins, sans contrainte.",
  "features.support.title": "Pilotez votre flotte IT",
  "features.support.desc": "Gérez et optimisez tout votre parc informatique depuis une interface unique.",

  // How it works section
  "how_it_works.title": "Comment ça marche",
  "how_it_works.subtitle": "Un processus simple et transparent pour équiper votre entreprise",
  "how_it_works.step1.title": "Choisissez votre équipement",
  "how_it_works.step1.desc": "Parcourez notre catalogue et sélectionnez les équipements adaptés à vos besoins.",
  "how_it_works.step2.title": "Définissez votre durée",
  "how_it_works.step2.desc": "Choisissez la durée de location qui vous convient, de 1 à 36 mois selon vos projets.",
  "how_it_works.step3.title": "Recevez et utilisez",
  "how_it_works.step3.desc":
    "Nous livrons et installons votre équipement. Profitez d'un support technique pendant toute la durée.",
  "how_it_works.step4.title": "Retournez ou renouvelez",
  "how_it_works.step4.desc": "En fin de contrat, retournez l'équipement ou renouvelez avec du matériel plus récent.",

  // Products section
  "products.title": "Nos équipements populaires",
  "products.subtitle": "Découvrez une sélection de nos équipements les plus demandés",
  "products.view_all": "Voir tout le catalogue",

  // Catalogue
  "catalogue.title": "Notre catalogue",
  "catalogue.subtitle": "Découvrez tous nos équipements professionnels disponibles en location",
  "catalogue.search_placeholder": "Rechercher un équipement...",
  "catalogue.filter_by_category": "Filtrer par catégorie",
  "catalogue.all_categories": "Toutes les catégories",
  "catalogue.sort_by": "Trier par",
  "catalogue.sort.popularity": "Popularité",
  "catalogue.sort.price_asc": "Prix croissant",
  "catalogue.sort.price_desc": "Prix décroissant",
  "catalogue.sort.newest": "Plus récents",
  "catalogue.no_products": "Aucun produit trouvé",
  "catalogue.no_products_description": "Essayez de modifier vos critères de recherche",

  // Category pages
  "category.breadcrumb.home": "Accueil",
  "category.breadcrumb.catalog": "Catalogue",
  "category.back_to_catalog": "Retour au catalogue",
  "category.product_available": "produit disponible",
  "category.products_available": "produits disponibles",
  "category.find_equipment": "Trouvez l'équipement parfait pour vos besoins professionnels.",
  "category.sort_by": "Trier par :",
  "category.sort.popularity": "Popularité",
  "category.sort.price_asc": "Prix croissant",
  "category.sort.price_desc": "Prix décroissant",
  "category.sort.newest": "Plus récents",
  "category.no_products": "Aucun produit trouvé",
  "category.no_products_description": "Aucun produit ne correspond à vos critères de recherche.",
  "category.why_rent_title": "Pourquoi louer vos {category} ?",
  "category.why_rent_description": "La location vous offre flexibilité, économies et tranquillité d'esprit.",
  "category.benefit1.title": "Économies garanties",
  "category.benefit1.description": "Réduisez vos coûts d'investissement et préservez votre trésorerie.",
  "category.benefit2.title": "Toujours à jour",
  "category.benefit2.description": "Bénéficiez des dernières technologies sans obsolescence.",
  "category.benefit3.title": "Support inclus",
  "category.benefit3.description": "Maintenance et support technique inclus dans votre contrat.",
  "category.cta.title": "Prêt à équiper votre entreprise ?",
  "category.cta.description": "Contactez-nous pour obtenir un devis personnalisé et découvrir nos solutions.",
  "category.cta.button1": "Demander un devis",
  "category.cta.button2": "Nous contacter",

  // Footer
  "footer.company": "Entreprise",
  "footer.about": "À propos",
  "footer.careers": "Carrières",
  "footer.press": "Presse",
  "footer.support": "Support",
  "footer.help": "Aide",
  "footer.contact": "Contact",
  "footer.faq": "FAQ",
  "footer.legal": "Légal",
  "footer.privacy": "Confidentialité",
  "footer.terms": "Conditions",
  "footer.cookies": "Cookies",
  "footer.follow": "Suivez-nous",
  "footer.newsletter": "Newsletter",
  "footer.newsletter_desc": "Restez informé de nos dernières offres",
  "footer.subscribe": "S'abonner",
  "footer.rights": "Tous droits réservés.",

  // Common
  "common.loading": "Chargement...",
  "common.error": "Une erreur est survenue",
  "common.retry": "Réessayer",
  "common.close": "Fermer",
  "common.save": "Enregistrer",
  "common.cancel": "Annuler",
  "common.confirm": "Confirmer",
  "common.delete": "Supprimer",
  "common.edit": "Modifier",
  "common.view": "Voir",
  "common.back": "Retour",
  "common.next": "Suivant",
  "common.previous": "Précédent",
  "common.search": "Rechercher",
  "common.filter": "Filtrer",
  "common.sort": "Trier",
  "common.reset": "Réinitialiser",
  "common.apply": "Appliquer",
  "common.clear": "Effacer",
  "common.select": "Sélectionner",
  "common.deselect": "Désélectionner",
  "common.all": "Tout",
  "common.none": "Aucun",
  "common.yes": "Oui",
  "common.no": "Non",
  "common.ok": "OK",
  "common.submit": "Envoyer",
  "common.send": "Envoyer",
  "common.receive": "Recevoir",
  "common.download": "Télécharger",
  "common.upload": "Téléverser",
  "common.print": "Imprimer",
  "common.share": "Partager",
  "common.copy": "Copier",
  "common.paste": "Coller",
  "common.cut": "Couper",
  "common.undo": "Annuler",
  "common.redo": "Refaire",
  "common.refresh": "Actualiser",
  "common.reload": "Recharger",
  "common.update": "Mettre à jour",
  "common.upgrade": "Mettre à niveau",
  "common.downgrade": "Rétrograder",
  "common.install": "Installer",
  "common.uninstall": "Désinstaller",
  "common.configure": "Configurer",
  "common.settings": "Paramètres",
  "common.preferences": "Préférences",
  "common.options": "Options",
  "common.tools": "Outils",
  "common.utilities": "Utilitaires",
  "common.help": "Aide",
  "common.support": "Support",
  "common.documentation": "Documentation",
  "common.tutorial": "Tutoriel",
  "common.guide": "Guide",
  "common.manual": "Manuel",
  "common.faq": "FAQ",
  "common.contact": "Contact",
  "common.feedback": "Commentaires",
  "common.report": "Signaler",
  "common.bug": "Bug",
  "common.feature": "Fonctionnalité",
  "common.request": "Demande",
  "common.suggestion": "Suggestion",
  "common.improvement": "Amélioration",
  "common.enhancement": "Amélioration",
  "common.optimization": "Optimisation",
  "common.performance": "Performance",
  "common.speed": "Vitesse",
  "common.quality": "Qualité",
  "common.reliability": "Fiabilité",
  "common.stability": "Stabilité",
  "common.security": "Sécurité",
  "common.privacy": "Confidentialité",
  "common.safety": "Sécurité",
  "common.protection": "Protection",
  "common.backup": "Sauvegarde",
  "common.restore": "Restaurer",
  "common.recover": "Récupérer",
  "common.repair": "Réparer",
  "common.fix": "Corriger",
  "common.solve": "Résoudre",
  "common.troubleshoot": "Dépanner",
  "common.diagnose": "Diagnostiquer",
  "common.analyze": "Analyser",
  "common.monitor": "Surveiller",
  "common.track": "Suivre",
  "common.log": "Journal",
  "common.history": "Historique",
  "common.record": "Enregistrement",
  "common.archive": "Archive",
  "common.storage": "Stockage",
  "common.memory": "Mémoire",
  "common.disk": "Disque",
  "common.space": "Espace",
  "common.capacity": "Capacité",
  "common.usage": "Utilisation",
  "common.consumption": "Consommation",
  "common.resource": "Ressource",
  "common.allocation": "Allocation",
  "common.distribution": "Distribution",
  "common.balance": "Équilibre",
  "common.optimization": "Optimisation",
  "common.efficiency": "Efficacité",
  "common.productivity": "Productivité",
  "common.workflow": "Flux de travail",
  "common.process": "Processus",
  "common.procedure": "Procédure",
  "common.method": "Méthode",
  "common.approach": "Approche",
  "common.strategy": "Stratégie",
  "common.plan": "Plan",
  "common.schedule": "Planification",
  "common.timeline": "Chronologie",
  "common.deadline": "Date limite",
  "common.milestone": "Jalon",
  "common.goal": "Objectif",
  "common.target": "Cible",
  "common.objective": "Objectif",
  "common.purpose": "But",
  "common.mission": "Mission",
  "common.vision": "Vision",
  "common.value": "Valeur",
  "common.principle": "Principe",
  "common.standard": "Standard",
  "common.guideline": "Directive",
  "common.policy": "Politique",
  "common.rule": "Règle",
  "common.regulation": "Réglementation",
  "common.compliance": "Conformité",
  "common.requirement": "Exigence",
  "common.specification": "Spécification",
  "common.criteria": "Critères",
  "common.condition": "Condition",
  "common.term": "Terme",
  "common.agreement": "Accord",
  "common.contract": "Contrat",
  "common.license": "Licence",
  "common.permission": "Permission",
  "common.authorization": "Autorisation",
  "common.access": "Accès",
  "common.login": "Connexion",
  "common.logout": "Déconnexion",
  "common.signin": "Se connecter",
  "common.signout": "Se déconnecter",
  "common.signup": "S'inscrire",
  "common.register": "S'enregistrer",
  "common.account": "Compte",
  "common.profile": "Profil",
  "common.user": "Utilisateur",
  "common.admin": "Administrateur",
  "common.manager": "Gestionnaire",
  "common.operator": "Opérateur",
  "common.guest": "Invité",
  "common.member": "Membre",
  "common.customer": "Client",
  "common.client": "Client",
  "common.vendor": "Fournisseur",
  "common.supplier": "Fournisseur",
  "common.partner": "Partenaire",
  "common.stakeholder": "Partie prenante",
  "common.team": "Équipe",
  "common.group": "Groupe",
  "common.organization": "Organisation",
  "common.company": "Entreprise",
  "common.business": "Entreprise",
  "common.corporation": "Corporation",
  "common.enterprise": "Entreprise",
  "common.firm": "Firme",
  "common.agency": "Agence",
  "common.department": "Département",
  "common.division": "Division",
  "common.unit": "Unité",
  "common.branch": "Branche",
  "common.office": "Bureau",
  "common.location": "Emplacement",
  "common.site": "Site",
  "common.facility": "Installation",
  "common.building": "Bâtiment",
  "common.floor": "Étage",
  "common.room": "Salle",
  "common.area": "Zone",
  "common.region": "Région",
  "common.country": "Pays",
  "common.city": "Ville",
  "common.address": "Adresse",
  "common.phone": "Téléphone",
  "common.email": "Email",
  "common.website": "Site web",
  "common.url": "URL",
  "common.link": "Lien",
  "common.reference": "Référence",
  "common.source": "Source",
  "common.destination": "Destination",
  "common.origin": "Origine",
  "common.target": "Cible",
  "common.endpoint": "Point de terminaison",
  "common.interface": "Interface",
  "common.api": "API",
  "common.service": "Service",
  "common.application": "Application",
  "common.software": "Logiciel",
  "common.program": "Programme",
  "common.system": "Système",
  "common.platform": "Plateforme",
  "common.framework": "Framework",
  "common.library": "Bibliothèque",
  "common.module": "Module",
  "common.component": "Composant",
  "common.element": "Élément",
  "common.widget": "Widget",
  "common.control": "Contrôle",
  "common.button": "Bouton",
  "common.menu": "Menu",
  "common.toolbar": "Barre d'outils",
  "common.panel": "Panneau",
  "common.window": "Fenêtre",
  "common.dialog": "Dialogue",
  "common.popup": "Popup",
  "common.modal": "Modal",
  "common.form": "Formulaire",
  "common.field": "Champ",
  "common.input": "Entrée",
  "common.output": "Sortie",
  "common.result": "Résultat",
  "common.response": "Réponse",
  "common.feedback": "Retour",
  "common.message": "Message",
  "common.notification": "Notification",
  "common.alert": "Alerte",
  "common.warning": "Avertissement",
  "common.error": "Erreur",
  "common.exception": "Exception",
  "common.failure": "Échec",
  "common.success": "Succès",
  "common.completion": "Achèvement",
  "common.progress": "Progrès",
  "common.status": "Statut",
  "common.state": "État",
  "common.mode": "Mode",
  "common.type": "Type",
  "common.category": "Catégorie",
  "common.class": "Classe",
  "common.group": "Groupe",
  "common.set": "Ensemble",
  "common.collection": "Collection",
  "common.list": "Liste",
  "common.array": "Tableau",
  "common.table": "Tableau",
  "common.grid": "Grille",
  "common.chart": "Graphique",
  "common.graph": "Graphique",
  "common.diagram": "Diagramme",
  "common.map": "Carte",
  "common.image": "Image",
  "common.picture": "Image",
  "common.photo": "Photo",
  "common.video": "Vidéo",
  "common.audio": "Audio",
  "common.sound": "Son",
  "common.music": "Musique",
  "common.file": "Fichier",
  "common.document": "Document",
  "common.text": "Texte",
  "common.content": "Contenu",
  "common.data": "Données",
  "common.information": "Information",
  "common.detail": "Détail",
  "common.description": "Description",
  "common.summary": "Résumé",
  "common.overview": "Aperçu",
  "common.preview": "Aperçu",
  "common.review": "Révision",
  "common.check": "Vérifier",
  "common.verify": "Vérifier",
  "common.validate": "Valider",
  "common.confirm": "Confirmer",
  "common.approve": "Approuver",
  "common.reject": "Rejeter",
  "common.accept": "Accepter",
  "common.decline": "Décliner",
  "common.deny": "Refuser",
  "common.allow": "Autoriser",
  "common.permit": "Permettre",
  "common.enable": "Activer",
  "common.disable": "Désactiver",
  "common.activate": "Activer",
  "common.deactivate": "Désactiver",
  "common.start": "Démarrer",
  "common.stop": "Arrêter",
  "common.pause": "Pause",
  "common.resume": "Reprendre",
  "common.continue": "Continuer",
  "common.proceed": "Procéder",
  "common.advance": "Avancer",
  "common.move": "Déplacer",
  "common.navigate": "Naviguer",
  "common.go": "Aller",
  "common.come": "Venir",
  "common.return": "Retourner",
  "common.exit": "Sortir",
  "common.leave": "Quitter",
  "common.enter": "Entrer",
  "common.join": "Rejoindre",
  "common.connect": "Connecter",
  "common.disconnect": "Déconnecter",
  "common.link": "Lier",
  "common.unlink": "Délier",
  "common.attach": "Attacher",
  "common.detach": "Détacher",
  "common.bind": "Lier",
  "common.unbind": "Délier",
  "common.associate": "Associer",
  "common.disassociate": "Dissocier",
  "common.relate": "Relier",
  "common.unrelate": "Délier",
  "common.match": "Correspondre",
  "common.unmatch": "Ne pas correspondre",
  "common.pair": "Apparier",
  "common.unpair": "Désapparier",
  "common.merge": "Fusionner",
  "common.split": "Diviser",
  "common.combine": "Combiner",
  "common.separate": "Séparer",
  "common.unite": "Unir",
  "common.divide": "Diviser",
  "common.add": "Ajouter",
  "common.remove": "Supprimer",
  "common.insert": "Insérer",
  "common.delete": "Supprimer",
  "common.create": "Créer",
  "common.destroy": "Détruire",
  "common.build": "Construire",
  "common.demolish": "Démolir",
  "common.make": "Faire",
  "common.unmake": "Défaire",
  "common.do": "Faire",
  "common.undo": "Annuler",
  "common.perform": "Effectuer",
  "common.execute": "Exécuter",
  "common.run": "Exécuter",
  "common.launch": "Lancer",
  "common.open": "Ouvrir",
  "common.close": "Fermer",
  "common.show": "Afficher",
  "common.hide": "Masquer",
  "common.display": "Afficher",
  "common.conceal": "Cacher",
  "common.reveal": "Révéler",
  "common.expose": "Exposer",
  "common.cover": "Couvrir",
  "common.uncover": "Découvrir",
  "common.wrap": "Envelopper",
  "common.unwrap": "Déballer",
  "common.pack": "Emballer",
  "common.unpack": "Déballer",
  "common.compress": "Compresser",
  "common.decompress": "Décompresser",
  "common.expand": "Étendre",
  "common.collapse": "Réduire",
  "common.extend": "Étendre",
  "common.contract": "Contracter",
  "common.stretch": "Étirer",
  "common.shrink": "Rétrécir",
  "common.grow": "Grandir",
  "common.reduce": "Réduire",
  "common.increase": "Augmenter",
  "common.decrease": "Diminuer",
  "common.maximize": "Maximiser",
  "common.minimize": "Minimiser",
  "common.optimize": "Optimiser",
  "common.improve": "Améliorer",
  "common.enhance": "Améliorer",
  "common.upgrade": "Mettre à niveau",
  "common.downgrade": "Rétrograder",
  "common.promote": "Promouvoir",
  "common.demote": "Rétrograder",
  "common.elevate": "Élever",
  "common.lower": "Abaisser",
  "common.raise": "Élever",
  "common.drop": "Laisser tomber",
  "common.lift": "Soulever",
  "common.push": "Pousser",
  "common.pull": "Tirer",
  "common.drag": "Glisser",
  "common.drop": "Déposer",
  "common.pick": "Choisir",
  "common.choose": "Choisir",
  "common.select": "Sélectionner",
  "common.deselect": "Désélectionner",
  "common.mark": "Marquer",
  "common.unmark": "Démarquer",
  "common.check": "Cocher",
  "common.uncheck": "Décocher",
  "common.tick": "Cocher",
  "common.untick": "Décocher",
  "common.flag": "Marquer",
  "common.unflag": "Démarquer",
  "common.tag": "Étiqueter",
  "common.untag": "Désétiqueter",
  "common.label": "Étiqueter",
  "common.unlabel": "Désétiqueter",
  "common.name": "Nommer",
  "common.rename": "Renommer",
  "common.title": "Titre",
  "common.subtitle": "Sous-titre",
  "common.heading": "En-tête",
  "common.subheading": "Sous-en-tête",
  "common.caption": "Légende",
  "common.note": "Note",
  "common.comment": "Commentaire",
  "common.remark": "Remarque",
  "common.observation": "Observation",
  "common.feedback": "Retour",
  "common.opinion": "Opinion",
  "common.view": "Vue",
  "common.perspective": "Perspective",
  "common.angle": "Angle",
  "common.aspect": "Aspect",
  "common.facet": "Facette",
  "common.dimension": "Dimension",
  "common.scope": "Portée",
  "common.range": "Gamme",
  "common.extent": "Étendue",
  "common.limit": "Limite",
  "common.boundary": "Frontière",
  "common.border": "Bordure",
  "common.edge": "Bord",
  "common.margin": "Marge",
  "common.padding": "Rembourrage",
  "common.spacing": "Espacement",
  "common.gap": "Écart",
  "common.distance": "Distance",
  "common.length": "Longueur",
  "common.width": "Largeur",
  "common.height": "Hauteur",
  "common.depth": "Profondeur",
  "common.size": "Taille",
  "common.scale": "Échelle",
  "common.proportion": "Proportion",
  "common.ratio": "Ratio",
  "common.percentage": "Pourcentage",
  "common.fraction": "Fraction",
  "common.decimal": "Décimal",
  "common.number": "Nombre",
  "common.digit": "Chiffre",
  "common.figure": "Figure",
  "common.amount": "Montant",
  "common.quantity": "Quantité",
  "common.count": "Compte",
  "common.total": "Total",
  "common.sum": "Somme",
  "common.average": "Moyenne",
  "common.median": "Médiane",
  "common.minimum": "Minimum",
  "common.maximum": "Maximum",
  "common.range": "Plage",
  "common.variance": "Variance",
  "common.deviation": "Déviation",
  "common.standard": "Standard",
  "common.normal": "Normal",
  "common.regular": "Régulier",
  "common.typical": "Typique",
  "common.usual": "Habituel",
  "common.common": "Commun",
  "common.rare": "Rare",
  "common.unique": "Unique",
  "common.special": "Spécial",
  "common.custom": "Personnalisé",
  "common.default": "Par défaut",
  "common.automatic": "Automatique",
  "common.manual": "Manuel",
}

const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("fr")

  // Simple translation function with fallback
  const t = (key: string): string => {
    const translation = translations[key as keyof typeof translations]
    if (translation) {
      return translation
    }

    // Fallback: return the key itself if translation not found
    console.warn(`Translation missing for key: ${key}`)
    return key
  }

  const value = {
    language,
    setLanguage,
    t,
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { LanguageProvider }
