import type { Product, Category, Brand, Order, Customer, Supplier, Attribute } from "@/types/admin"

// Catégories
export const mockCategories: Category[] = [
  {
    id: "cat-laptops",
    name: "Ordinateurs portables",
    slug: "ordinateurs-portables",
    description: "Ordinateurs portables professionnels pour entreprises",
    parentId: null,
    image: "/images/macbook-pro.png",
    productCount: 3,
    isActive: true,
    order: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "cat-smartphones",
    name: "Smartphones",
    slug: "smartphones",
    description: "Smartphones professionnels",
    parentId: null,
    image: "/images/iphone.png",
    productCount: 1,
    isActive: true,
    order: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "cat-desktops",
    name: "Ordinateurs de bureau",
    slug: "ordinateurs-bureau",
    description: "Stations de travail professionnelles",
    parentId: null,
    image: "/images/imac.png",
    productCount: 1,
    isActive: true,
    order: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
]

// Marques
export const mockBrands: Brand[] = [
  {
    id: "brand-apple",
    name: "Apple",
    slug: "apple",
    description: "Produits Apple de qualité professionnelle",
    logo: "/images/logo-apple.png",
    website: "https://www.apple.com",
    isActive: true,
    productCount: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "brand-dell",
    name: "Dell",
    slug: "dell",
    description: "Ordinateurs professionnels Dell",
    logo: "/images/logo-dell.png",
    website: "https://www.dell.com",
    isActive: true,
    productCount: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
]

// Attributs
export const mockAttributes: Attribute[] = [
  {
    id: "attr-processor",
    name: "Processeur",
    slug: "processeur",
    type: "select",
    values: ["Intel Core i5", "Intel Core i7", "Intel Core i9", "Apple M2", "Apple M2 Pro", "Apple M3"],
    isRequired: true,
    isFilterable: true,
    order: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    categories: ["cat-laptops", "cat-desktops"],
  },
  {
    id: "attr-ram",
    name: "Mémoire RAM",
    slug: "ram",
    type: "select",
    values: ["8GB", "16GB", "32GB", "64GB"],
    isRequired: true,
    isFilterable: true,
    order: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    categories: ["cat-laptops", "cat-desktops"],
  },
  {
    id: "attr-storage",
    name: "Stockage",
    slug: "stockage",
    type: "select",
    values: ["256GB SSD", "512GB SSD", "1TB SSD", "2TB SSD"],
    isRequired: true,
    isFilterable: true,
    order: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    categories: ["cat-laptops", "cat-desktops", "cat-smartphones"],
  },
  {
    id: "attr-screen",
    name: "Écran",
    slug: "ecran",
    type: "select",
    values: ['13"', '14"', '15"', '16"', '24"', '27"'],
    isRequired: false,
    isFilterable: true,
    order: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    categories: ["cat-laptops", "cat-desktops"],
  },
  {
    id: "attr-color",
    name: "Couleur",
    slug: "couleur",
    type: "select",
    values: ["Gris sidéral", "Argent", "Or", "Noir", "Blanc"],
    isRequired: false,
    isFilterable: true,
    order: 5,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    categories: ["cat-laptops", "cat-smartphones", "cat-desktops"],
  },
]

// Produits
export const mockProducts: Product[] = [
  {
    id: "prod-mbp-14",
    sku: "MBP-14-001",
    name: "MacBook Pro 14",
    slug: "macbook-pro-14",
    shortDescription: "Ordinateur portable professionnel",
    description: "Le MacBook Pro 14 pouces est l'ordinateur portable parfait pour les professionnels exigeants.",
    price: 450,
    compareAtPrice: 500,
    costPrice: 350,
    categoryId: "cat-laptops",
    brandId: "brand-apple",
    thumbnail: "/images/macbook-pro.png",
    images: ["/images/macbook-pro.png"],
    stockQuantity: 15,
    lowStockThreshold: 5,
    status: "active",
    isFeatured: true,
    tags: ["laptop", "apple", "pro"],
    attributes: {
      "attr-processor": "Apple M2 Pro",
      "attr-ram": "16GB",
      "attr-storage": "512GB SSD",
      "attr-screen": '14"',
      "attr-color": "Gris sidéral",
    },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "prod-dell-xps",
    sku: "DELL-XPS-001",
    name: "Dell XPS 13",
    slug: "dell-xps-13",
    shortDescription: "Ultrabook professionnel Dell",
    description: "Le Dell XPS 13 combine performance et portabilité pour les professionnels en déplacement.",
    price: 380,
    costPrice: 280,
    categoryId: "cat-laptops",
    brandId: "brand-dell",
    thumbnail: "/images/dell-xps.png",
    images: ["/images/dell-xps.png"],
    stockQuantity: 20,
    lowStockThreshold: 5,
    status: "active",
    isFeatured: true,
    tags: ["laptop", "dell", "ultrabook"],
    attributes: {
      "attr-processor": "Intel Core i7",
      "attr-ram": "16GB",
      "attr-storage": "512GB SSD",
      "attr-screen": '13"',
      "attr-color": "Argent",
    },
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "prod-iphone-14",
    sku: "IPH-14P-001",
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    shortDescription: "Smartphone professionnel Apple",
    description: "L'iPhone 14 Pro offre des performances exceptionnelles pour les professionnels connectés.",
    price: 320,
    compareAtPrice: 350,
    costPrice: 250,
    categoryId: "cat-smartphones",
    brandId: "brand-apple",
    thumbnail: "/images/iphone.png",
    images: ["/images/iphone.png"],
    stockQuantity: 30,
    lowStockThreshold: 10,
    status: "active",
    isFeatured: true,
    tags: ["smartphone", "apple", "iphone"],
    attributes: {
      "attr-storage": "256GB SSD",
      "attr-color": "Gris sidéral",
    },
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "prod-dell-pre",
    sku: "DELL-PRE-001",
    name: "Dell Precision 5690",
    slug: "dell-precision-5690",
    shortDescription: "Station de travail mobile professionnelle",
    description:
      "La Dell Precision 5690 est une station de travail mobile haut de gamme conçue pour les professionnels exigeants.",
    price: 280,
    costPrice: 200,
    categoryId: "cat-laptops",
    brandId: "brand-dell",
    thumbnail: "/images/dell-precision-5690.png",
    images: [
      "/images/dell-precision-5690-main.png",
      "/images/dell-precision-5690-side.png",
      "/images/dell-precision-5690-keyboard.png",
    ],
    stockQuantity: 12,
    lowStockThreshold: 5,
    status: "active",
    isFeatured: false,
    tags: ["laptop", "dell", "workstation"],
    attributes: {
      "attr-processor": "Intel Core i9",
      "attr-ram": "32GB",
      "attr-storage": "1TB SSD",
      "attr-screen": '16"',
      "attr-color": "Noir",
    },
    createdAt: "2024-01-12T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "prod-imac-24",
    sku: "IMAC-24-001",
    name: "iMac 24",
    slug: "imac-24",
    shortDescription: "Ordinateur de bureau tout-en-un",
    description: "L'iMac 24 pouces combine design élégant et performances exceptionnelles pour votre bureau.",
    price: 520,
    compareAtPrice: 580,
    costPrice: 400,
    categoryId: "cat-desktops",
    brandId: "brand-apple",
    thumbnail: "/images/imac.png",
    images: ["/images/imac.png"],
    stockQuantity: 8,
    lowStockThreshold: 3,
    status: "active",
    isFeatured: true,
    tags: ["desktop", "apple", "imac"],
    attributes: {
      "attr-processor": "Apple M3",
      "attr-ram": "16GB",
      "attr-storage": "512GB SSD",
      "attr-screen": '24"',
      "attr-color": "Argent",
    },
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
]

// Commandes
export const mockOrders: Order[] = [
  {
    id: "order-001",
    orderNumber: "ORD-2024-001",
    customerId: "cust-001",
    customerName: "Société ABC",
    customerEmail: "contact@abc.ma",
    status: "delivered",
    paymentStatus: "paid",
    total: 1350,
    subtotal: 1350,
    tax: 0,
    shippingCost: 0,
    items: [
      {
        productId: "prod-mbp-14",
        productName: "MacBook Pro 14",
        sku: "MBP-14-001",
        quantity: 3,
        price: 450,
        total: 1350,
      },
    ],
    shippingAddress: {
      fullName: "Société ABC",
      company: "ABC SARL",
      address: "123 Boulevard Mohammed V",
      city: "Casablanca",
      postalCode: "20000",
      country: "Maroc",
      phone: "+212 5 22 00 00 00",
    },
    billingAddress: {
      fullName: "Société ABC",
      company: "ABC SARL",
      address: "123 Boulevard Mohammed V",
      city: "Casablanca",
      postalCode: "20000",
      country: "Maroc",
      phone: "+212 5 22 00 00 00",
    },
    notes: "Livraison urgente demandée",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T14:30:00Z",
    deliveredAt: "2024-01-15T14:30:00Z",
  },
  {
    id: "order-002",
    orderNumber: "ORD-2024-002",
    customerId: "cust-002",
    customerName: "Entreprise XYZ",
    customerEmail: "info@xyz.ma",
    status: "processing",
    paymentStatus: "paid",
    total: 760,
    subtotal: 760,
    tax: 0,
    shippingCost: 0,
    items: [
      {
        productId: "prod-dell-xps",
        productName: "Dell XPS 13",
        sku: "DELL-XPS-001",
        quantity: 2,
        price: 380,
        total: 760,
      },
    ],
    shippingAddress: {
      fullName: "Entreprise XYZ",
      company: "XYZ Corp",
      address: "456 Avenue Hassan II",
      city: "Rabat",
      postalCode: "10000",
      country: "Maroc",
      phone: "+212 5 37 00 00 00",
    },
    billingAddress: {
      fullName: "Entreprise XYZ",
      company: "XYZ Corp",
      address: "456 Avenue Hassan II",
      city: "Rabat",
      postalCode: "10000",
      country: "Maroc",
      phone: "+212 5 37 00 00 00",
    },
    createdAt: "2024-01-12T15:00:00Z",
    updatedAt: "2024-01-12T15:30:00Z",
  },
  {
    id: "order-003",
    orderNumber: "ORD-2024-003",
    customerId: "cust-003",
    customerName: "Tech Solutions",
    customerEmail: "contact@techsolutions.ma",
    status: "pending",
    paymentStatus: "pending",
    total: 960,
    subtotal: 960,
    tax: 0,
    shippingCost: 0,
    items: [
      {
        productId: "prod-iphone-14",
        productName: "iPhone 14 Pro",
        sku: "IPH-14P-001",
        quantity: 3,
        price: 320,
        total: 960,
      },
    ],
    shippingAddress: {
      fullName: "Tech Solutions",
      company: "Tech Solutions SARL",
      address: "789 Rue Prince Moulay Abdellah",
      city: "Marrakech",
      postalCode: "40000",
      country: "Maroc",
      phone: "+212 5 24 00 00 00",
    },
    billingAddress: {
      fullName: "Tech Solutions",
      company: "Tech Solutions SARL",
      address: "789 Rue Prince Moulay Abdellah",
      city: "Marrakech",
      postalCode: "40000",
      country: "Maroc",
      phone: "+212 5 24 00 00 00",
    },
    createdAt: "2024-01-14T09:00:00Z",
    updatedAt: "2024-01-14T09:00:00Z",
  },
  {
    id: "order-004",
    orderNumber: "ORD-2024-004",
    customerId: "cust-004",
    customerName: "Digital Innovations",
    customerEmail: "hello@digitalinnovations.ma",
    status: "delivered",
    paymentStatus: "paid",
    total: 520,
    subtotal: 520,
    tax: 0,
    shippingCost: 0,
    items: [
      {
        productId: "prod-imac-24",
        productName: "iMac 24",
        sku: "IMAC-24-001",
        quantity: 1,
        price: 520,
        total: 520,
      },
    ],
    shippingAddress: {
      fullName: "Digital Innovations",
      company: "DI Group",
      address: "321 Boulevard Zerktouni",
      city: "Casablanca",
      postalCode: "20000",
      country: "Maroc",
      phone: "+212 5 22 11 11 11",
    },
    billingAddress: {
      fullName: "Digital Innovations",
      company: "DI Group",
      address: "321 Boulevard Zerktouni",
      city: "Casablanca",
      postalCode: "20000",
      country: "Maroc",
      phone: "+212 5 22 11 11 11",
    },
    createdAt: "2024-01-08T11:00:00Z",
    updatedAt: "2024-01-10T16:00:00Z",
    deliveredAt: "2024-01-10T16:00:00Z",
  },
  {
    id: "order-005",
    orderNumber: "ORD-2024-005",
    customerId: "cust-002",
    customerName: "Entreprise XYZ",
    customerEmail: "info@xyz.ma",
    status: "processing",
    paymentStatus: "paid",
    total: 840,
    subtotal: 840,
    tax: 0,
    shippingCost: 0,
    items: [
      {
        productId: "prod-dell-pre",
        productName: "Dell Precision 5690",
        sku: "DELL-PRE-001",
        quantity: 3,
        price: 280,
        total: 840,
      },
    ],
    shippingAddress: {
      fullName: "Entreprise XYZ",
      company: "XYZ Corp",
      address: "456 Avenue Hassan II",
      city: "Rabat",
      postalCode: "10000",
      country: "Maroc",
      phone: "+212 5 37 00 00 00",
    },
    billingAddress: {
      fullName: "Entreprise XYZ",
      company: "XYZ Corp",
      address: "456 Avenue Hassan II",
      city: "Rabat",
      postalCode: "10000",
      country: "Maroc",
      phone: "+212 5 37 00 00 00",
    },
    createdAt: "2024-01-13T14:00:00Z",
    updatedAt: "2024-01-13T14:30:00Z",
  },
]

// Clients
export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    firstName: "Mohammed",
    lastName: "Alami",
    email: "contact@abc.ma",
    phone: "+212 5 22 00 00 00",
    company: "Société ABC",
    taxId: "123456789",
    type: "business",
    status: "active",
    totalOrders: 1,
    totalSpent: 1350,
    averageOrderValue: 1350,
    addresses: [
      {
        id: "addr-001",
        type: "billing",
        fullName: "Société ABC",
        company: "ABC SARL",
        address: "123 Boulevard Mohammed V",
        city: "Casablanca",
        postalCode: "20000",
        country: "Maroc",
        phone: "+212 5 22 00 00 00",
        isDefault: true,
      },
    ],
    notes: "Client premium avec contrat annuel",
    tags: ["premium", "b2b"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    lastOrderAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "cust-002",
    firstName: "Fatima",
    lastName: "Benani",
    email: "info@xyz.ma",
    phone: "+212 5 37 00 00 00",
    company: "Entreprise XYZ",
    taxId: "987654321",
    type: "business",
    status: "active",
    totalOrders: 2,
    totalSpent: 1600,
    averageOrderValue: 800,
    addresses: [
      {
        id: "addr-002",
        type: "billing",
        fullName: "Entreprise XYZ",
        company: "XYZ Corp",
        address: "456 Avenue Hassan II",
        city: "Rabat",
        postalCode: "10000",
        country: "Maroc",
        phone: "+212 5 37 00 00 00",
        isDefault: true,
      },
    ],
    notes: "Client régulier depuis 2023",
    tags: ["regular", "b2b"],
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-13T00:00:00Z",
    lastOrderAt: "2024-01-13T14:00:00Z",
  },
  {
    id: "cust-003",
    firstName: "Youssef",
    lastName: "Tazi",
    email: "contact@techsolutions.ma",
    phone: "+212 5 24 00 00 00",
    company: "Tech Solutions",
    taxId: "456789123",
    type: "business",
    status: "active",
    totalOrders: 1,
    totalSpent: 960,
    averageOrderValue: 960,
    addresses: [
      {
        id: "addr-003",
        type: "billing",
        fullName: "Tech Solutions",
        company: "Tech Solutions SARL",
        address: "789 Rue Prince Moulay Abdellah",
        city: "Marrakech",
        postalCode: "40000",
        country: "Maroc",
        phone: "+212 5 24 00 00 00",
        isDefault: true,
      },
    ],
    tags: ["new", "b2b"],
    createdAt: "2024-01-14T00:00:00Z",
    updatedAt: "2024-01-14T00:00:00Z",
    lastOrderAt: "2024-01-14T09:00:00Z",
  },
  {
    id: "cust-004",
    firstName: "Amina",
    lastName: "Idrissi",
    email: "hello@digitalinnovations.ma",
    phone: "+212 5 22 11 11 11",
    company: "Digital Innovations",
    taxId: "789123456",
    type: "business",
    status: "active",
    totalOrders: 1,
    totalSpent: 520,
    averageOrderValue: 520,
    addresses: [
      {
        id: "addr-004",
        type: "billing",
        fullName: "Digital Innovations",
        company: "DI Group",
        address: "321 Boulevard Zerktouni",
        city: "Casablanca",
        postalCode: "20000",
        country: "Maroc",
        phone: "+212 5 22 11 11 11",
        isDefault: true,
      },
    ],
    tags: ["premium", "b2b"],
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
    lastOrderAt: "2024-01-08T11:00:00Z",
  },
]

// Fournisseurs
export const mockSuppliers: Supplier[] = [
  {
    id: "supp-001",
    name: "Apple Distribution Maroc",
    email: "contact@apple-maroc.ma",
    phone: "+212 5 22 99 99 99",
    website: "https://www.apple.com/ma",
    address: {
      address: "Twin Center, Tour A",
      city: "Casablanca",
      postalCode: "20000",
      country: "Maroc",
    },
    contactPerson: "Hassan Benjelloun",
    taxId: "111222333",
    status: "active",
    productsSupplied: ["MacBook Pro 14", "iPhone 14 Pro", "iMac 24"],
    paymentTerms: "Net 30",
    notes: "Distributeur officiel Apple au Maroc",
    tags: ["apple", "premium"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "supp-002",
    name: "Dell Enterprise Maroc",
    email: "sales@dell-maroc.ma",
    phone: "+212 5 37 88 88 88",
    website: "https://www.dell.com/ma",
    address: {
      address: "Technopolis Rabat Shore",
      city: "Rabat",
      postalCode: "10000",
      country: "Maroc",
    },
    contactPerson: "Sara Alaoui",
    taxId: "444555666",
    status: "active",
    productsSupplied: ["Dell XPS 13", "Dell Precision 5690"],
    paymentTerms: "Net 45",
    notes: "Partenaire Dell certifié",
    tags: ["dell", "enterprise"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
]

// Statistiques du tableau de bord
export const mockDashboardStats = {
  revenue: {
    total: 4430,
    change: 12.5,
  },
  orders: {
    total: 5,
    change: 8.3,
  },
  customers: {
    total: 4,
    change: 15.2,
  },
  products: {
    total: 5,
    change: 0,
  },
}

// Données de ventes pour le graphique
export const mockSalesData = [
  { date: "2024-01-08", revenue: 520 },
  { date: "2024-01-10", revenue: 1870 },
  { date: "2024-01-12", revenue: 760 },
  { date: "2024-01-13", revenue: 840 },
  { date: "2024-01-14", revenue: 960 },
]
